### ISSUE TITLE
Rewrite rules matcher should match asynchronously 

### ISSUE THREAD

**Issue by RazinShaikh** [zxcalc/zxlive#110]
When we select a subgraph in the proof mode, it calls the matcher of rewrite rules. This should happen async, otherwise when we have a lot of rewrite rules, it can make the UI unresponsive while the matchers for all the rules are being called.

**Comment by jvdwetering** [comment]
I agree. But also, when we put rules into different tabs/categories, you could only run the matcher for the rewrites in the currently selected tab.
