### ISSUE TITLE
Multi-edge and fusion

### ISSUE THREAD

**Issue by pandey-tushar** [zxcalc/zxlive#17]
- [x] Create multi edge style graph
- [x] Self-loops
- [x] Fusion rule for multi edges + self loops

**Comment by RazinShaikh** [comment]
This should be implemented in [pyzx](https://github.com/Quantomatic/pyzx). Looks like there is already a branch: https://github.com/Quantomatic/pyzx/tree/multigraph

**Comment by RazinShaikh** [comment]
This is now supported.
