### ISSUE TITLE
Implement bialgebra in the other direction

### ISSUE THREAD

**Issue by y-richie-y** [zxcalc/zxlive#20]
Right now we can only apply bialgebra in only one direction, which reduces the number of nodes.
Sometimes the other direction is desirable.

**Comment by RazinShaikh** [comment]
I closed this issue when I implemented custom rewrites in zxlive. But since the custom rewrites do not yet support rewrites with dots or arbitrary arity (see #109 ), it is still useful to implement this version of bialgebra. So I am reopening this issue.

**Comment by RazinShaikh** [comment]
Implemented in f1f15a6e07e210c2ab7d457261833661adedf39c
