### ISSUE TITLE
Improve selection support

### ISSUE THREAD

**Issue by akissinger** [zxcalc/zxlive#23]
Currently selection behaviour is a bit shonky. I suggest we:

- [x] replace ad hoc selection data with built in selection support from [QGraphicsScene](https://doc.qt.io/qt-6/qgraphicsscene.html#selectedItems) and [QGraphicsItem](https://doc.qt.io/qt-6/qgraphicsitem.html#isSelected)
- [x] handle selection and deselection consistently
- [x] implement multiple selection, both with shift+clicking and rectangular selection
- [x] deal with multiple selections correctly when moving/deleting nodes
- [ ] #186

**Comment by jvdwetering** [comment]
Many things here fixed by PR #37

**Comment by jvdwetering** [comment]
Rectangular selection is now supported, but shift-clicking is not. The Qt default is control-clicking. It is probably not too difficult to also allow shift-clicking.
I'm not sure what exactly you mean by preserving selection state across undo/redo. That you automatically support the part of the graph that was reverted back by the undo? Or that changes of selection also go on the undo stack? Or that an undo remembers what the state was of the selection at the moment the action of the undo happened, and then when you undo it reverts back to this selection state?

**Comment by RazinShaikh** [comment]
I am closing this collection as we have a decent support for selection now and the last remaining point "maintain selection state across undo/redo" can be tracked in its own issue at https://github.com/zxcalc/zxlive/issues/186
