### ISSUE TITLE
Increase font size of the ZXLive UI?

### ISSUE THREAD

**Issue by RazinShaikh** [zxcalc/zxlive#278]
Is it just me or do other people also find the default font size of the ZXLive UI a bit too small?

**Comment by boldar99** [comment]
<img width="1199" alt="image" src="https://github.com/zxcalc/zxlive/assets/49209650/69440415-754f-4082-b42a-8fb207882073">

I have managed to add font family and font size settings (see Input Circuit). The question is how many font groups do we want to create?

We can:
- make every font the same across the whole application
- Have maybe 2 font styles. One for fonts in edit_panels, and another for everything outside.

What do you think @RazinShaikh?

**Comment by RazinShaikh** [comment]
What is the reasoning behind a different font for the edit panel?

**Comment by boldar99** [comment]
One example that I like to look for inspiration for UI design is PyCharm. They have 3 classes to change fonts: for the application settings, for the editor, and one for the terminal.
For us, it could also make sense to set the general font to anything and editor-font to some mono/sans font

**Comment by RazinShaikh** [comment]
I don't really have an opinion about the circuit input font as I have not used it much so I am happy with your suggested change. I am mainly bothered by the font size of tab names, menu bar, rewrite rules, etc.
In the screenshot you sent previously, compare the font size of "start derivation" button the "new graph" tab.
Alternatively, when I put ZXLive side-by-side with something else like vs code, I find that ZXLive is a bit small for my preference.
![image](https://github.com/zxcalc/zxlive/assets/28257517/d9d4f7d4-26e4-4184-a989-347d1a0d8913)
For things like rewrite rules, I also wish that it was more space out vertically because it feels a bit cramed.
<img src="https://github.com/zxcalc/zxlive/assets/28257517/87bd2e3f-6717-4f90-8630-4dff9be9c152" width=250/>
