### ISSUE TITLE
Bialgebra rewrites from "basic rules" and drag-and-drop result in different global scalars

### ISSUE THREAD

**Issue by RazinShaikh** [zxcalc/zxlive#314]
For instance, apply both bialgebra rewrites on the following diagram and observe the scalar on the top left corner.
<img width=250 src=https://github.com/zxcalc/zxlive/assets/28257517/d98a6fd2-5b8d-4929-aec7-a7388b854317/>
The basic rules version and the drag-and-drop version show 2.0 and 1.41 respectively.

**Comment by jvdwetering** [comment]
Is this a bug in the pyzx implementation?

**Comment by RazinShaikh** [comment]
I have figured out the error. In the PR zxcalc/pyzx#248 I changed basicrules.py version to call the editor_actions.py bialgebra, so both rewrites are calling the same pyzx method under the hood. But both functions originally had slightly different assumptions; such as the first vertex out of the two was always an X spider.
I need to change the following block
```python
        if g.type(v2) == VertexType.Z:
            g.scalar.add_power((g.vertex_degree(v1)-2)*(g.vertex_degree(v2)-2))
        else: #g.type(w) == VertexType.H_BOX
            g.scalar.add_power(g.vertex_degree(v1)-2)
``` 
to
```python
        if g.type(v1) == VertexType.H_BOX or g.type(v2) == VertexType.H_BOX: # x-h bialgebra
            x_vertex = v1 if g.type(v2) == VertexType.H_BOX else v2
            g.scalar.add_power(g.vertex_degree(x_vertex)-2)
        else: # z-x bialgebra
            g.scalar.add_power((g.vertex_degree(v1)-2)*(g.vertex_degree(v2)-2))
```
