### ISSUE TITLE
Add boolean settings form input

### ISSUE THREAD

**Issue by boldar99** [zxcalc/zxlive#321]
Potentially with a toggle box or toggle switch.

Steps:

1. Add `Bool` to `FormInputType`
2. Implement `SettingsDialog.make_bool_form_input`
3. Add it to `add_setting_to_form`
4. Change all the boolean settings to use the new implementation.
5. Add hidden settings like sparkle mode and sound effects (If done)

**Comment by jvdwetering** [comment]
This is implemented, but currently broken: the settings aren't actually saved.
